### ISSUE TITLE
0xBB packet not being picked up by other mods

### ISSUE THREAD

**Issue by mckyle099** [Revan600/Diablo-II-Item-Mover#6]
Hi @Revan600 , I am building off v1.04 and am trying to capture the 0xBB s->c packet from another mod, but I seem to only get two 0xA8 packets instead, any idea what I’m doing wrong? Thanks.

**Comment by Revan600** [comment]
If it's still a thing, you want to change line #34 in d2tweaks/common/protocol.h (https://github.com/Revan600/d2tweaks/blob/13a2cb39ddc92723997058dce33269aa8bc131c5/include/d2tweaks/common/protocol.h#L34)
